spring.application.name=api-gateway
server.port=8080

# Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Swagger (gateway can aggregate if needed)
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false